-- 0016_capture_annotations_and_recordings.sql
--
-- Three threads, all hung off the capture record:
--
--   1. Operator annotation. `description` (0015) is the free-form note; this adds
--      a structured `observation_type` (what kind of thing was seen) and
--      `severity`. Set at capture time or edited later (captures.update). Distinct
--      from model output.
--   2. Auto "brief details". `inferred_summary` holds a short agronomic blurb
--      generated by the new optional `summary` pipeline stage (Claude) from the
--      RT-DETR + PlantNet detections. Kept separate from operator `description`
--      so the blurb never clobbers human text. Mirrors `inferred_species`.
--   3. Live-feed recordings. `kind` distinguishes a normal observation from a
--      saved live-session recording (a video capture). Portal recordings arrive
--      with a new `portal_recording` source; phone recordings keep
--      `field_capture_pwa` + kind='session_recording'.
--
-- Plus: register the `agronomic_summary` model + append it to default-plant@v2
-- as an optional (required=false) summary stage, and widen the pipeline_stages
-- role check to allow 'summary'.
--
-- Idempotent: safe to re-run.
--
-- Apply via: psql "$DATABASE_URL" -f packages/db/migrations/0016_capture_annotations_and_recordings.sql
-- (or paste into the Supabase SQL editor).
------------------------------------------------------------------------------

------------------------------------------------------------------------
-- 1. Capture annotation + recording columns
------------------------------------------------------------------------

alter table public.captures
  add column if not exists observation_type text
    check (observation_type in (
      'pest', 'disease', 'weed', 'nutrient',
      'irrigation', 'damage', 'growth_stage', 'other'
    )),
  add column if not exists severity text
    check (severity in ('low', 'medium', 'high')),
  add column if not exists kind text not null default 'observation'
    check (kind in ('observation', 'session_recording')),
  -- Model-authored brief details (agronomic blurb). Distinct from operator
  -- `description` and from raw `inferred_species`.
  add column if not exists inferred_summary text;

-- Filter index for the portal Recordings section (kind='session_recording').
create index if not exists captures_org_kind_idx
  on public.captures (org_id, kind);

------------------------------------------------------------------------
-- 2. Allow portal-originated recordings as a capture source.
--    The inline check from 0004 is auto-named captures_source_check.
------------------------------------------------------------------------

alter table public.captures
  drop constraint if exists captures_source_check;

alter table public.captures
  add constraint captures_source_check check (source in (
    'field_capture_pwa',
    'bulk_upload',
    'portal_recording',   -- a watcher recorded the live WebRTC stream from the portal
    'gaia_r',
    'gaia_d',
    'gaia_s',
    'integration'
  ));

------------------------------------------------------------------------
-- 3. Allow a 'summary' pipeline stage role.
--    The inline check from 0009 is auto-named pipeline_stages_role_check.
------------------------------------------------------------------------

alter table public.pipeline_stages
  drop constraint if exists pipeline_stages_role_check;

alter table public.pipeline_stages
  add constraint pipeline_stages_role_check check (role in (
    'detection',
    'classification',
    'refinement',
    'filter',
    'summary'        -- post-classification natural-language synthesis (LLM)
  ));

------------------------------------------------------------------------
-- 4. Register the agronomic-summary model.
--    The concrete Claude model id lives in the stage config (swappable
--    without a migration); this row is the registry handle the vision
--    StageRegistry resolves (name, version) against.
------------------------------------------------------------------------

insert into public.model_versions (
  name, version, task, framework, external_provider,
  artifact_uri, training_data_snapshot_id, eval_metrics,
  status, promoted_at, notes
) values (
  'agronomic_summary',
  'v1',
  'plant_classification',
  'external_api',
  'anthropic',
  null,
  null,
  '{}'::jsonb,
  'production',
  now(),
  'Optional summary stage in default-plant@v2. Reads the RT-DETR + PlantNet detections and asks Claude for a 1-2 sentence agronomic brief (likely issues, growth-stage cues). Optional: when ANTHROPIC_API_KEY is unset the stage reports unconfigured and the pipeline still succeeds. The concrete model id is in pipeline_stages.config.model.'
)
on conflict (name, version) do nothing;

------------------------------------------------------------------------
-- 5. Append the summary stage to default-plant@v2 (optional, last).
------------------------------------------------------------------------

do $$
declare
  v_pipeline_id   uuid;
  v_summary_id    uuid;
  v_exists        boolean;
begin
  select id into v_pipeline_id
    from public.pipelines
    where name = 'default-plant' and version = 'v2';
  if v_pipeline_id is null then
    raise exception 'expected default-plant@v2 in pipelines';
  end if;

  select id into v_summary_id
    from public.model_versions
    where name = 'agronomic_summary' and version = 'v1';
  if v_summary_id is null then
    raise exception 'expected agronomic_summary@v1 in model_versions';
  end if;

  -- Idempotent: only append if this pipeline doesn't already have the stage.
  select exists (
    select 1 from public.pipeline_stages
    where pipeline_id = v_pipeline_id and model_version_id = v_summary_id
  ) into v_exists;

  if not v_exists then
    insert into public.pipeline_stages (
      pipeline_id, stage_order, role, model_version_id, config, enabled, required
    ) values (
      -- Stage 3: agronomic summary. Optional — if ANTHROPIC_API_KEY is unset
      -- or the call fails, the pipeline still succeeds with species + detections.
      v_pipeline_id, 3, 'summary', v_summary_id,
      '{"model": "claude-sonnet-4-6", "max_tokens": 200}'::jsonb,
      true, false
    );
  end if;
end$$;
